package com.tripshield.api;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

/**
 * Gemini API Client (Api.java)
 * Integrates directly with the official Google developer Gemini AI endpoints
 * using standard Java 11+ HttpClient and raw JSON structures.
 */
@Component
public class GeminiApiClient {

    @Value("${gemini.api.key:}")
    private String apiKey;

    private static final String GEMINI_API_URL = "https://generativelink.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent";
    private final HttpClient httpClient;

    public GeminiApiClient() {
        this.httpClient = HttpClient.newBuilder()
                .connectTimeout(Duration.ofSeconds(10))
                .build();
    }

    /**
     * Sends a generation prompt to the Gemini API and extracts the raw textual response.
     * Uses the recommended Gemini model alias 'gemini-2.5-flash'.
     *
     * @param prompt The safety situation context/instruction prompt.
     * @return The text result generated by Gemini, or a localized static safe fallback on failure.
     */
    public String queryGeminiModel(String prompt) {
        // Handle missing key gracefully to prevent booting crashes
        if (apiKey == null || apiKey.trim().isEmpty()) {
            apiKey = System.getenv("GEMINI_API_KEY");
        }
        
        if (apiKey == null || apiKey.trim().isEmpty()) {
            return "[FALLBACK SAFETY MESSAGE] Warning: GEMINI_API_KEY secret is not declared in your environment.\n" +
                   "Please stay calm. Keep your location shared. Try to reach the nearest local police station or embassy " +
                   "using the Safe Zones mapping visualizer.";
        }

        try {
            // Construct the standardized Gemini API JSON payload
            String sanitizedPrompt = prompt.replace("\"", "\\\"").replace("\n", "\\n");
            String jsonPayload = "{"
                    + "\"contents\": [{"
                    + "  \"parts\": [{"
                    + "    \"text\": \"" + sanitizedPrompt + "\""
                    + "  }]"
                    + "}]"
                    + "}";

            URI targetUri = URI.create(GEMINI_API_URL + "?key=" + apiKey);

            HttpRequest request = HttpRequest.newBuilder()
                    .uri(targetUri)
                    .header("Content-Type", "application/json")
                    .POST(HttpRequest.BodyPublishers.ofString(jsonPayload))
                    .timeout(Duration.ofSeconds(15))
                    .build();

            HttpResponse<String> response = httpClient.send(request, HttpResponse.BodyHandlers.ofString());

            if (response.statusCode() == 200) {
                return parseTextResponse(response.body());
            } else {
                System.err.println("Gemini API error. Status: " + response.statusCode() + " Body: " + response.body());
                return getStaticSafetyProtocol(prompt);
            }

        } catch (Exception e) {
            System.err.println("Failed to execute request to Gemini API gateway: " + e.getMessage());
            return getStaticSafetyProtocol(prompt);
        }
    }

    /**
     * Simple JSON parser to extract candidate text from Google's response body.
     */
    private String parseTextResponse(String json) {
        try {
            // Find content of "text": "..." within the candidates block
            int textIndex = json.indexOf("\"text\":");
            if (textIndex != -1) {
                int start = json.indexOf("\"", textIndex + 7) + 1;
                int end = json.indexOf("\"", start);
                String rawText = json.substring(start, end);
                
                // Clean up escape characters from JSON response
                return rawText.replace("\\n", "\n")
                               .replace("\\\"", "\"")
                               .replace("\\\\", "\\");
            }
        } catch (Exception e) {
            System.err.println("Failed to parse Gemini JSON payload: " + e.getMessage());
        }
        return json;
    }

    /**
     * Reliable local static emergency helper protocols in case the network connection
     * gets fully severed during tactical evasion.
     */
    private String getStaticSafetyProtocol(String prompt) {
        if (prompt.contains("SOS") || prompt.contains("emergency")) {
            return "TACTICAL LOCAL ESCAPE INSTRUCTIONS:\n" +
                   "1. De-escalate immediately. Comply with demands if dealing with robbery/extortion.\n" +
                   "2. Navigate swiftly to the nearest hospital or government safe zone marked on your radar.\n" +
                   "3. Tap the 'Secure Line' phone icon on the map coordinates overlay to dial the police directly.";
        }
        return "1. Trust your instincts and walk away from crowded alleys.\n" +
               "2. Do not show flashing luxury items, cash stacks, or expensive jewelry.\n" +
               "3. Verify active official safe nodes and maintain cellular contact.";
    }
}
